default_platform(:ios)

platform :ios do
  desc "Capture App Store screenshots"
  lane :screenshots do
    capture_screenshots
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    deliver(
      skip_binary_upload: true,
      skip_metadata: true,
      overwrite_screenshots: true,
      screenshots_path: "./fastlane/screenshots"
    )
  end
end
